# yaml for POD
apiVersion: v1
kind: Pod
metadata:
  name: Multi-pod-1
spec: 
  containers:
  - name: nginx1 
    image: nginx
    ports:
    - containerport: 80
    
  - name: nginx2
    image: nginx
    ports:
    - containerPort: 80