apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx  
  labels:
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx 
        image: nginx
        ports: 
        - Container: 80